### PR TITLE
Fix json generator for array fields with field options (issue #193)

### LINKED ISSUE #193: Bad JSON for multi-value fields
When I try `document.add_field(indexed_name, ['value1', 'value2'],{boost: 5})` rsolr will build JSON with has a bad format, Solr returns __Error parsing JSON field value. Unexpected OBJECT_STAR__

Here is a sample JSON, which causes problems
```JSON
{
  "id": "User 12",
  "type": [
    "User",
    "Searchable::SearchableUser",
    "ApplicationRecord",
    "ActiveRecord::Base"
  ],
  "class_name": "User",
  "id_is": "12",
  "name_ss": "field service officer user",
  "mobile_ss": "255760000009",
  "disabled_bs": "false",
  "created_at_dts": "2018-03-16T09:54:07Z",
  "id_text_texts": {
    "boost": 5,
    "value": "12"
  },
  "user_texts_texts": [
    {
      "boost": 5,
      "value": "user12@me.com"
    },
    {
      "boost": 5,
      "value": "255760000009"
    }
  ]
}
```
An error will be __Error parsing JSON field value. Unexpected OBJECT_START at [744], field=user_texts_texts__

I believe a proper format should be:
```
  "user_texts_texts": {
      "boost": 5,
      "value": ["user12@me.com", "255760000009"]
    }
```

### PR DESCRIPTION
**Pull request by serggl**
this attempts to fix #193 (Bad JSON for multi-value fields)

### CODE REVIEW

**Comment by LeandroTk** [comment]
Would be great to have a new version on rubygem!

**Comment by LeandroTk** [comment]
@mwmitchell @serggl @jcoyne It would be great to have a new version on rubygems!

**Comment by fabiwerneck** [comment]
Yes @LeandroTk! It would be really great to have a new version on rubygems!
cc @mwmitchell @serggl @jcoyne

**Comment by jcoyne** [comment]
I pushed 2.2.0. Sorry for the delay.

**Comment by fabiwerneck** [comment]
Thanks a lot @jcoyne :)

**Comment by rajeev-learningmate** [comment]
Hello All
I am using sunspot_solr (2.2.0)  and whenever I am running Model.reindex then it is throwing error like..

irb(main):001:0> Book::Page.reindex
D, [2018-06-05T06:05:33.947926 #6612] DEBUG -- :   SOLR Request (8.9ms)  [ path=update parameters={} ]
  Book::Page Load (0.3ms)  SELECT  `book_pages`.* FROM `book_pages`  ORDER BY `book_pages`.`id` ASC LIMIT 50
[2018-06-05 06:05:33 +0000] Start Indexing
D, [2018-06-05T06:05:34.506263 #6612] DEBUG -- :   SOLR Request (492.7ms)  [ path=update parameters={} ]
RSolr::Error::Http: RSolr::Error::Http - 400 Bad Request
Error: {'responseHeader'=>{'status'=>400,'QTime'=>480},'error'=>{'msg'=>'Illegal character ((CTRL-CHAR, code 7))
 at [row,col {unknown-source}]: [544,4]','code'=>400}}

URI: http://localhost:8982/solr/development/update?wt=ruby
Request Headers: {"Content-Type"=>"text/xml"}
Request Data: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><add><doc><f

**Pull request merged**
