### PR TITLE
use webmock instead of solr_wrapper

### PR DESCRIPTION
**Pull request by adjam**
Integration tests are currrently failing under CI, but this appears to be due to failures somewhere in `solr_wrapper`; since the existing integration tests don't really require a Solr instance, we can mock them while still exercising parts of the `rsolr` API.

### CODE REVIEW

**Comment by adjam** [comment]
see https://github.com/adjam/rsolr/pull/2 for CI results.

**Comment by cbeer** [comment]
I'm pretty uncomfortable testing rsolr against only mocks.

**Comment by adjam** [comment]
That is a fair point, and it is what made me hesitate suggesting this change.  The existing tests in the affected file don't currently involve Solr (there are tests ensuring that a ping to a collection returns a blank HTTP 200, and another ensuring that an attempt to connect to the wrong port is correctly wrapped).

Not depicted here are failed attempts to make use of a Solr service container in the CI action and wrap that in the CI environment only (using `solr_wrapper` locally) and delving into `solr_wrapper` to see why the JRuby tests might be failing there.  You may be better positioned to investigate what might be up with solr_wrapper.

**Comment by adjam** [comment]
Removed the 'ping' tests, kept the error wrapping test.

**Comment by jrochkind** [comment]
is this just veto'd and should be closed then? @cbeer ?

I appreciate @adjam's attempts to get towards tests green. 

We are unable to figure out how to get JRuby test green so far. What should we do? 

I guess if this is still true 6 months from now, I'll propose dropping JRuby from CI/support? (There are no docs on what versions of ruby RSolr supports).

**Comment by jrochkind** [comment]
I did approve running CI for this for you @adjam , will be curious to see if it makes tests pass on JRuby.

**Comment by jcoyne** [comment]
#221 made the tests green.

**Comment by jrochkind** [comment]
Oh wow, ruby 2.4 is green now too somehow. thank you!!

**Comment by cbeer** [comment]
Closing in favor of #221.

**Pull request closed without merging**
