### PR TITLE
[fixes #200] Fix JSON generator for atomic updates of array fields

### LINKED ISSUE #200: Bad JSON for array atomic updates
When I try `document.add_field(indexed_name, ['value1', 'value2'],{update: :set})` rsolr will build JSON in a wrong manner, so Solr returns __Error parsing JSON field value. Unexpected OBJECT_START__

Here is a sample JSON, which is being produced for the sample above 
```JSON
{
  "id": "Post 917", 
  "type": ["Post"], 
  "tag_list_sms": [
    {"set": "value 1"}, 
    {"set": "value 2"}
  ]
}
```
An error will be 
```
     RSolr::Error::Http:
       RSolr::Error::Http - 400 Bad Request
       Error: {"responseHeader":{"status":400,"QTime":3},"error":{"msg":"Error parsing JSON field value. Unexpected OBJECT_START at [77], field=tag_list_sms","code":400}}
     
       URI: http://localhost:8983/solr/default/update?wt=json
       Request Headers: {"Content-Type"=>"application/json"}
```

I believe a proper format should be:
```
  "tag_list_sms": {
      "set": ["value 1", "value 2"]
    }
```

### PR DESCRIPTION
**Pull request by serggl**
this attempts to fix #200 (Bad JSON for atomic update) and implementation is very similar to #194

### CODE REVIEW

**Comment by serggl** [comment]
@jcoyn @cbeer would you mind reviewing this? thanks

**Comment by serggl** [comment]
@cbeer I think the issue here is how `.add_field` is handling array values. It creates `Field` record for each array entry, not sure what was the original intent of this, perhaps to support XML protocol, but not sure. IMO opinion it would be good to invest some time to review this behaviour and consider this PR as just a short-term solution (hot fix)

**Comment by serggl** [comment]
@cbeer back to your original review: I've added support for more atomic operations which handle array values. This should also work with nested document updates. 
Can you please review again? Thanks

**Comment by allenwu1973** [comment]
@cbeer We've been hit by this issue too, is there anyway we can help to get this merged?

**Review by bess — APPROVED** [review]

**Comment by jrochkind** [comment]
This will be in soon to be released rsolr 2.4.0. I sympathize with the inconvenience of the delay @allenwu1973 and @serggl !

**Pull request merged**
